/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package fjmobi;

import common.ButtonTabComponent;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;

/**
 *
 * @author linq
 */
public class MainForm extends javax.swing.JFrame {

    private TreeModel funcTreeModel;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        //设置图标
        Toolkit tk = Toolkit.getDefaultToolkit();
        Image image = tk.createImage(getClass().getResource("/fjmobi/images/xbmc.png")); //设置您的窗体标题上的图标
        this.setIconImage(image);
        //配置树
        final DefaultMutableTreeNode root = new DefaultMutableTreeNode();
        DefaultMutableTreeNode n;
        root.add(n = new DefaultMutableTreeNode("功能"));
        n.add(new Item("余额欠费查询", "fjmobi.BalanceArrears"));
        n.add(new Item("停机复机", "shutdownOpen"));
        n.add(new Item("缴费历史", "arrearsHistory"));
        root.add(n = new DefaultMutableTreeNode("系统"));
        n.add(new Item("验证码", "maskSymb"));
        n.add(new Item("参数", "pramas"));
        funcTreeModel = new DefaultTreeModel(root);
        initComponents();
        //tree.setRootVisible(false);
        //splitMain.setRightComponent(viewBoard);
        viewBoard.add("首页", new NumManager());
        //viewBoard.setTabComponentAt(0,new ButtonTabComponent(viewBoard));
        viewBoard.applyComponentOrientation(SwingUtilities.getRoot(this).getComponentOrientation());
        viewBoard.revalidate();
        viewBoard.repaint();
        splitMain.repaint();
    }

    private static class Item extends DefaultMutableTreeNode {

        private String label;
        private String clazz;
        private JComponent component;

        public Item(String label, String clazz) {
            this.label = label;
            this.clazz = clazz;
        }

        @Override
        public String toString() {
            return label;
        }

        public JComponent getComponent() {
            if (component == null) {
                try {
                    component = (JComponent) Class.forName(clazz).newInstance();
                } catch (Throwable ex) {
                    component = new JLabel(ex.toString());
                    ex.printStackTrace();
                }
            }
            return component;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        splitMain = new javax.swing.JSplitPane();
        treePanel = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        viewBoard = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("移动自动系统");
        setBackground(java.awt.SystemColor.controlDkShadow);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("文泉驿微米黑", 0, 14)); // NOI18N
        setForeground(java.awt.Color.red);
        setIconImages(null);
        setResizable(false);

        toolbar.setFloatable(false);
        toolbar.setRollover(true);
        toolbar.setBorderPainted(false);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fjmobi/images/gnome-shutdown.png"))); // NOI18N
        jButton2.setToolTipText("启动所有任务");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        toolbar.add(jButton2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fjmobi/images/media-playlist-shuffle.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(jButton1);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fjmobi/images/media-playback-pause.png"))); // NOI18N
        jButton3.setToolTipText("暂停所有任务");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fjmobi/images/gnome-app-install-star.png"))); // NOI18N
        jButton4.setToolTipText("帮助");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(jButton4);

        splitMain.setDividerLocation(160);
        splitMain.setPreferredSize(new java.awt.Dimension(300, 324));

        tree.setFont(tree.getFont());
        tree.setModel(funcTreeModel);
        tree.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeMouseClicked(evt);
            }
        });
        tree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeValueChanged(evt);
            }
        });
        treePanel.setViewportView(tree);

        splitMain.setLeftComponent(treePanel);

        viewBoard.setBorder(null);
        splitMain.setRightComponent(viewBoard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(splitMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitMain, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void treeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeMouseClicked
    }//GEN-LAST:event_treeMouseClicked

    private void treeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeValueChanged
        //JOptionPane.showMessageDialog(this, evt.getNewLeadSelectionPath().getLastPathComponent()); //提示框
        Object o = (Object) evt.getNewLeadSelectionPath().getLastPathComponent();
        if (o instanceof Item) {
            Item leaf = (Item) o;
            //存在的就不用调用了，OK？
            //JOptionPane.showMessageDialog(this,leaf.clazz); //提示框
            viewBoard.add(leaf.label, leaf.getComponent());
            viewBoard.applyComponentOrientation(SwingUtilities.getRoot(this).getComponentOrientation());
            viewBoard.setTabComponentAt(viewBoard.getTabCount()-1,new ButtonTabComponent(viewBoard));
        }
        viewBoard.revalidate();
        viewBoard.repaint();
    }//GEN-LAST:event_treeValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws NoSuchMethodException, InstantiationException {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JSplitPane splitMain;
    private javax.swing.JToolBar toolbar;
    private javax.swing.JTree tree;
    private javax.swing.JScrollPane treePanel;
    private javax.swing.JTabbedPane viewBoard;
    // End of variables declaration//GEN-END:variables
}
